virt-install \
      --nographics \
      --name v-de5233a85a.vps.cloudhybrid.io \
      --ram 512 \
      --disk path=/mnt/vCloud-1/Infrastructure/Virtual-Machines/v-de5233a85a.vps.cloudhybrid.io.qcow2,size=10 \
      --location "/mnt/vCloud-1/Infrastructure/Virtual-Machines/Bionic-Server.iso" \
      --initrd-inject=/mnt/vCloud-1/Infrastructure/Virtual-Machines/preseed.cfg \
      --vcpus 1 \
      --os-type linux \
      --os-variant ubuntu18.04 \
      --autostart \
      --extra-args="console=tty0,19200"
